apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: cicd
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS messages (
        id INT AUTO_INCREMENT PRIMARY KEY,
        message TEXT
    );
