apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: adishanbhag/flask-app:latest
        imagePullPolicy: Always
        env:
        - name: MYSQL_HOST
          value: "mysql"          # This should match your MySQL service name
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "admin"
        - name: MYSQL_DB
          value: "myDb"
        ports:
        - containerPort: 5000
