apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name:  mysql-ctr
        image: mysql
        imagePullPolicy: Always
        env:
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "admin"
        - name: MYSQL_DB
          value: "myDb"
        - name: MYSQL_ROOT_PASSWORD
          value: admin                # ✅ REQUIRED
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysqldata
            mountPath: /var/lib/mysql    # MySQL data directory inside container
      volumes:
      - name: mysqldata
        persistentVolumeClaim:
          claimName: mysql-pvc          # PVC must exist


